name: CI testing

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
      - 'docs/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: pip install --upgrade pip poetry

      - name: Install poetry
        run: poetry install

      - name: Run make ci
        run: make ci

      - name: Coveralls
        run: poetry run coveralls --service=github
